# Mnist Dataseet
The MNIST dataset is a widely used dataset in the field of machine learning and computer vision. It consists of 70,000 grayscale images of handwritten digits (0-9), with each image being 28x28 pixels in size. The dataset is commonly used for training and testing various machine learning algorithms, particularly in the context of image classification tasks.

In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

### Loading the dataset

In [4]:
# Loading the Data 
df = pd.read_csv('train_for_mnist.csv')
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Describing the dataset

In [5]:
# Shape (rows, columns)
print(f"Dataset has {df.shape[0]} rows and {df.shape[1]} columns.")

# Column names
print("\nColumns:", df.columns.tolist())

# Data types
print("\nData types:")
print(df.dtypes)

# Summary statistics
df.describe()

Dataset has 42000 rows and 785 columns.

Columns: ['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6', 'pixel7', 'pixel8', 'pixel9', 'pixel10', 'pixel11', 'pixel12', 'pixel13', 'pixel14', 'pixel15', 'pixel16', 'pixel17', 'pixel18', 'pixel19', 'pixel20', 'pixel21', 'pixel22', 'pixel23', 'pixel24', 'pixel25', 'pixel26', 'pixel27', 'pixel28', 'pixel29', 'pixel30', 'pixel31', 'pixel32', 'pixel33', 'pixel34', 'pixel35', 'pixel36', 'pixel37', 'pixel38', 'pixel39', 'pixel40', 'pixel41', 'pixel42', 'pixel43', 'pixel44', 'pixel45', 'pixel46', 'pixel47', 'pixel48', 'pixel49', 'pixel50', 'pixel51', 'pixel52', 'pixel53', 'pixel54', 'pixel55', 'pixel56', 'pixel57', 'pixel58', 'pixel59', 'pixel60', 'pixel61', 'pixel62', 'pixel63', 'pixel64', 'pixel65', 'pixel66', 'pixel67', 'pixel68', 'pixel69', 'pixel70', 'pixel71', 'pixel72', 'pixel73', 'pixel74', 'pixel75', 'pixel76', 'pixel77', 'pixel78', 'pixel79', 'pixel80', 'pixel81', 'pixel82', 'pixel83', 'pixel84', 'pixel85', 'pixel86', 'pixel87', 'pixel88', 'pixel89', 'pixel90', 'pixel91', 'pixel92', 'pixel93', 'pixel94', 'pixel95', 'pixel96', 'pixel97', 'pixel98', 'pixel99', 'pixel100', 'pixel101', 'pixel102', 'pixel103', 'pixel104', 'pixel105', 'pixel106', 'pixel107', 'pixel108', 'pixel109', 'pixel110', 'pixel111', 'pixel112', 'pixel113', 'pixel114', 'pixel115', 'pixel116', 'pixel117', 'pixel118', 'pixel119', 'pixel120', 'pixel121', 'pixel122', 'pixel123', 'pixel124', 'pixel125', 'pixel126', 'pixel127', 'pixel128', 'pixel129', 'pixel130', 'pixel131', 'pixel132', 'pixel133', 'pixel134', 'pixel135', 'pixel136', 'pixel137', 'pixel138', 'pixel139', 'pixel140', 'pixel141', 'pixel142', 'pixel143', 'pixel144', 'pixel145', 'pixel146', 'pixel147', 'pixel148', 'pixel149', 'pixel150', 'pixel151', 'pixel152', 'pixel153', 'pixel154', 'pixel155', 'pixel156', 'pixel157', 'pixel158', 'pixel159', 'pixel160', 'pixel161', 'pixel162', 'pixel163', 'pixel164', 'pixel165', 'pixel166', 'pixel167', 'pixel168', 'pixel169', 'pixel170', 'pixel171', 'pixel172', 'pixel173', 'pixel174', 'pixel175', 'pixel176', 'pixel177', 'pixel178', 'pixel179', 'pixel180', 'pixel181', 'pixel182', 'pixel183', 'pixel184', 'pixel185', 'pixel186', 'pixel187', 'pixel188', 'pixel189', 'pixel190', 'pixel191', 'pixel192', 'pixel193', 'pixel194', 'pixel195', 'pixel196', 'pixel197', 'pixel198', 'pixel199', 'pixel200', 'pixel201', 'pixel202', 'pixel203', 'pixel204', 'pixel205', 'pixel206', 'pixel207', 'pixel208', 'pixel209', 'pixel210', 'pixel211', 'pixel212', 'pixel213', 'pixel214', 'pixel215', 'pixel216', 'pixel217', 'pixel218', 'pixel219', 'pixel220', 'pixel221', 'pixel222', 'pixel223', 'pixel224', 'pixel225', 'pixel226', 'pixel227', 'pixel228', 'pixel229', 'pixel230', 'pixel231', 'pixel232', 'pixel233', 'pixel234', 'pixel235', 'pixel236', 'pixel237', 'pixel238', 'pixel239', 'pixel240', 'pixel241', 'pixel242', 'pixel243', 'pixel244', 'pixel245', 'pixel246', 'pixel247', 'pixel248', 'pixel249', 'pixel250', 'pixel251', 'pixel252', 'pixel253', 'pixel254', 'pixel255', 'pixel256', 'pixel257', 'pixel258', 'pixel259', 'pixel260', 'pixel261', 'pixel262', 'pixel263', 'pixel264', 'pixel265', 'pixel266', 'pixel267', 'pixel268', 'pixel269', 'pixel270', 'pixel271', 'pixel272', 'pixel273', 'pixel274', 'pixel275', 'pixel276', 'pixel277', 'pixel278', 'pixel279', 'pixel280', 'pixel281', 'pixel282', 'pixel283', 'pixel284', 'pixel285', 'pixel286', 'pixel287', 'pixel288', 'pixel289', 'pixel290', 'pixel291', 'pixel292', 'pixel293', 'pixel294', 'pixel295', 'pixel296', 'pixel297', 'pixel298', 'pixel299', 'pixel300', 'pixel301', 'pixel302', 'pixel303', 'pixel304', 'pixel305', 'pixel306', 'pixel307', 'pixel308', 'pixel309', 'pixel310', 'pixel311', 'pixel312', 'pixel313', 'pixel314', 'pixel315', 'pixel316', 'pixel317', 'pixel318', 'pixel319', 'pixel320', 'pixel321', 'pixel322', 'pixel323', 'pixel324', 'pixel325', 'pixel326', 'pixel327', 'pixel328', 'pixel329', 'pixel330', 'pixel331', 'pixel332', 'pixel333', 'pixel334', 'pixel335', 'pixel336', 'pixel337', 'pixel338', 'pixel339', 'pixel340', 'pixel341', 'pixel342', 'pixel343', 'pixel344', 'pixel345', 'pixel346', 'pixel347', 'pixel348', 'pixel349', 'pixel350', 'pixel351', 'pixel352', 'pixel353', 'pixel354', 'pixel355', 'pixel356', 'pixel357', 'pixel358', 'pixel359', 'pixel360', 'pixel361', 'pixel362', 'pixel363', 'pixel364', 'pixel365', 'pixel366', 'pixel367', 'pixel368', 'pixel369', 'pixel370', 'pixel371', 'pixel372', 'pixel373', 'pixel374', 'pixel375', 'pixel376', 'pixel377', 'pixel378', 'pixel379', 'pixel380', 'pixel381', 'pixel382', 'pixel383', 'pixel384', 'pixel385', 'pixel386', 'pixel387', 'pixel388', 'pixel389', 'pixel390', 'pixel391', 'pixel392', 'pixel393', 'pixel394', 'pixel395', 'pixel396', 'pixel397', 'pixel398', 'pixel399', 'pixel400', 'pixel401', 'pixel402', 'pixel403', 'pixel404', 'pixel405', 'pixel406', 'pixel407', 'pixel408', 'pixel409', 'pixel410', 'pixel411', 'pixel412', 'pixel413', 'pixel414', 'pixel415', 'pixel416', 'pixel417', 'pixel418', 'pixel419', 'pixel420', 'pixel421', 'pixel422', 'pixel423', 'pixel424', 'pixel425', 'pixel426', 'pixel427', 'pixel428', 'pixel429', 'pixel430', 'pixel431', 'pixel432', 'pixel433', 'pixel434', 'pixel435', 'pixel436', 'pixel437', 'pixel438', 'pixel439', 'pixel440', 'pixel441', 'pixel442', 'pixel443', 'pixel444', 'pixel445', 'pixel446', 'pixel447', 'pixel448', 'pixel449', 'pixel450', 'pixel451', 'pixel452', 'pixel453', 'pixel454', 'pixel455', 'pixel456', 'pixel457', 'pixel458', 'pixel459', 'pixel460', 'pixel461', 'pixel462', 'pixel463', 'pixel464', 'pixel465', 'pixel466', 'pixel467', 'pixel468', 'pixel469', 'pixel470', 'pixel471', 'pixel472', 'pixel473', 'pixel474', 'pixel475', 'pixel476', 'pixel477', 'pixel478', 'pixel479', 'pixel480', 'pixel481', 'pixel482', 'pixel483', 'pixel484', 'pixel485', 'pixel486', 'pixel487', 'pixel488', 'pixel489', 'pixel490', 'pixel491', 'pixel492', 'pixel493', 'pixel494', 'pixel495', 'pixel496', 'pixel497', 'pixel498', 'pixel499', 'pixel500', 'pixel501', 'pixel502', 'pixel503', 'pixel504', 'pixel505', 'pixel506', 'pixel507', 'pixel508', 'pixel509', 'pixel510', 'pixel511', 'pixel512', 'pixel513', 'pixel514', 'pixel515', 'pixel516', 'pixel517', 'pixel518', 'pixel519', 'pixel520', 'pixel521', 'pixel522', 'pixel523', 'pixel524', 'pixel525', 'pixel526', 'pixel527', 'pixel528', 'pixel529', 'pixel530', 'pixel531', 'pixel532', 'pixel533', 'pixel534', 'pixel535', 'pixel536', 'pixel537', 'pixel538', 'pixel539', 'pixel540', 'pixel541', 'pixel542', 'pixel543', 'pixel544', 'pixel545', 'pixel546', 'pixel547', 'pixel548', 'pixel549', 'pixel550', 'pixel551', 'pixel552', 'pixel553', 'pixel554', 'pixel555', 'pixel556', 'pixel557', 'pixel558', 'pixel559', 'pixel560', 'pixel561', 'pixel562', 'pixel563', 'pixel564', 'pixel565', 'pixel566', 'pixel567', 'pixel568', 'pixel569', 'pixel570', 'pixel571', 'pixel572', 'pixel573', 'pixel574', 'pixel575', 'pixel576', 'pixel577', 'pixel578', 'pixel579', 'pixel580', 'pixel581', 'pixel582', 'pixel583', 'pixel584', 'pixel585', 'pixel586', 'pixel587', 'pixel588', 'pixel589', 'pixel590', 'pixel591', 'pixel592', 'pixel593', 'pixel594', 'pixel595', 'pixel596', 'pixel597', 'pixel598', 'pixel599', 'pixel600', 'pixel601', 'pixel602', 'pixel603', 'pixel604', 'pixel605', 'pixel606', 'pixel607', 'pixel608', 'pixel609', 'pixel610', 'pixel611', 'pixel612', 'pixel613', 'pixel614', 'pixel615', 'pixel616', 'pixel617', 'pixel618', 'pixel619', 'pixel620', 'pixel621', 'pixel622', 'pixel623', 'pixel624', 'pixel625', 'pixel626', 'pixel627', 'pixel628', 'pixel629', 'pixel630', 'pixel631', 'pixel632', 'pixel633', 'pixel634', 'pixel635', 'pixel636', 'pixel637', 'pixel638', 'pixel639', 'pixel640', 'pixel641', 'pixel642', 'pixel643', 'pixel644', 'pixel645', 'pixel646', 'pixel647', 'pixel648', 'pixel649', 'pixel650', 'pixel651', 'pixel652', 'pixel653', 'pixel654', 'pixel655', 'pixel656', 'pixel657', 'pixel658', 'pixel659', 'pixel660', 'pixel661', 'pixel662', 'pixel663', 'pixel664', 'pixel665', 'pixel666', 'pixel667', 'pixel668', 'pixel669', 'pixel670', 'pixel671', 'pixel672', 'pixel673', 'pixel674', 'pixel675', 'pixel676', 'pixel677', 'pixel678', 'pixel679', 'pixel680', 'pixel681', 'pixel682', 'pixel683', 'pixel684', 'pixel685', 'pixel686', 'pixel687', 'pixel688', 'pixel689', 'pixel690', 'pixel691', 'pixel692', 'pixel693', 'pixel694', 'pixel695', 'pixel696', 'pixel697', 'pixel698', 'pixel699', 'pixel700', 'pixel701', 'pixel702', 'pixel703', 'pixel704', 'pixel705', 'pixel706', 'pixel707', 'pixel708', 'pixel709', 'pixel710', 'pixel711', 'pixel712', 'pixel713', 'pixel714', 'pixel715', 'pixel716', 'pixel717', 'pixel718', 'pixel719', 'pixel720', 'pixel721', 'pixel722', 'pixel723', 'pixel724', 'pixel725', 'pixel726', 'pixel727', 'pixel728', 'pixel729', 'pixel730', 'pixel731', 'pixel732', 'pixel733', 'pixel734', 'pixel735', 'pixel736', 'pixel737', 'pixel738', 'pixel739', 'pixel740', 'pixel741', 'pixel742', 'pixel743', 'pixel744', 'pixel745', 'pixel746', 'pixel747', 'pixel748', 'pixel749', 'pixel750', 'pixel751', 'pixel752', 'pixel753', 'pixel754', 'pixel755', 'pixel756', 'pixel757', 'pixel758', 'pixel759', 'pixel760', 'pixel761', 'pixel762', 'pixel763', 'pixel764', 'pixel765', 'pixel766', 'pixel767', 'pixel768', 'pixel769', 'pixel770', 'pixel771', 'pixel772', 'pixel773', 'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780', 'pixel781', 'pixel782', 'pixel783']

Data types:
label       int64
pixel0      int64
pixel1      int64
pixel2      int64
pixel3      int64
            ...
pixel779    int64
pixel780    int64
pixel781    int64
pixel782    int64
pixel783    int64
Length: 785, dtype: object

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

### Finding the Label in the dataset

In [6]:
print(df.shape)
print(df.columns[:5])
print(df.columns[-5:])
print('label' in df.columns)

(42000, 785)
Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3'], dtype='object')
Index(['pixel779', 'pixel780', 'pixel781', 'pixel782', 'pixel783'], dtype='object')
True

## Checking for Missing Values

In [7]:
df.isna().sum().sum() # This dataset has no missing values due to the fact that it is a clean dataset.

np.int64(0)

## Removing those columns which are not required for the model training or are continously Zero

In [8]:
pixel_cols = [c for c in df.columns if c.startswith("pixel")]
all_zero_cols = [c for c in pixel_cols if (df[c] == 0).all()]
len(all_zero_cols), all_zero_cols[:10]
df = df.drop(columns=all_zero_cols)
print("Those columns which are continously zero and not required for model training have been removed.")

Those columns which are continously zero and not required for model training have been removed.

In [9]:
print(f"Dataset has {df.shape[0]} rows and {df.shape[1]} columns.")

Dataset has 42000 rows and 709 columns.

## Normalizing the features and separating the target variable from the features

In [10]:
pixel_cols = [c for c in df.columns if c.startswith("pixel")]

X = df[pixel_cols].astype(np.float32)
y = df["label"]  # or whatever the target column is called

X = X / 255.0
print("Features (X) and target (y) have been separated and features have been normalized.")

Features (X) and target (y) have been separated and features have been normalized.

## Train/ Test Split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

Train shape: (33600, 708) Test shape: (8400, 708)

## Evaluation Function

In [12]:
def evaluate_model(model, X_test, y_test, name="model", show_report=True, show_cm=True):
    """
    Fits are done outside this function.
    This function evaluates on X_test/y_test and prints:
    - accuracy
    - classification report
    - confusion matrix
    """
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print(f"\n{name} Results")
    print("-" * (len(name) + 8))
    print("Accuracy:", round(acc, 4))

    if show_report:
        print("\nClassification report:")
        print(classification_report(y_test, y_pred))

    if show_cm:
        print("Confusion matrix:")
        print(confusion_matrix(y_test, y_pred))

    return acc

# Model Training and Evaluation

# KNN 
**Idea:**  
“To classify something new, look at the most similar things you’ve seen before, and copy the most common label.”

**Simple example (movies):**  
You want to guess a movie genre for a new movie.
- You look for the **5 most similar movies** (similar length, similar amount of action, similar humor).
- If **3 out of 5** are “Action”, you predict **Action**.

**How this relates to MNIST digits:**  
For a new handwritten digit image, k‑NN compares it with many saved images and says:
- “Which saved images look most similar to this one?”
- Then it takes a vote: if most similar ones are “7”, it predicts **7**.

**Strengths (in simple words):**
- Easy to understand.
- Often works decently as a baseline.

**Weaknesses (in simple words):**
- Can be **slow**, because it has to compare the new image to lots of old images.

In [13]:
knn_pipe = Pipeline([
    ("scaler", StandardScaler(with_mean=False) if hasattr(X_train, "toarray") else StandardScaler()),
    ("model", KNeighborsClassifier(n_neighbors=5))
])

# SVM 
**Idea:**  
“Draw the cleanest boundary that separates categories.”

Imagine you have points on a sheet:
- Red points = “cats”
- Blue points = “dogs”  
SVM tries to draw a line (or boundary) that separates them with the best “gap” between groups.

**Simple example (two fruits):**
You want to separate apples and oranges using two measurements:
- sweetness
- sourness  
SVM tries to find the best boundary so that apples fall on one side and oranges on the other.

**How this relates to MNIST digits:**
Each image has 784 pixel values. SVM tries to learn rules that separate digits:
- “This pattern looks like 0”
- “That pattern looks like 3”
- etc.

**Strengths (in simple words):**
- Often very accurate for many problems.
- Good at separating classes when the pattern is clear.

**Weaknesses (in simple words):**
- Can be **slow** on large image datasets (lots of rows and many pixel columns).
- Images are complex, and classical methods can struggle to capture “shape” the way humans see it.

In [14]:
svm_pipe = Pipeline([
    ("scaler", StandardScaler(with_mean=False) if hasattr(X_train, "toarray") else StandardScaler()),
    ("model", LinearSVC(random_state=42))
])

# Naive Bayes
**Idea:**  
“Use many small clues to guess the most likely category.”

**Simple example (spam detection):**
- If an email contains “free” → that’s a clue for spam
- If it contains “winner” → another clue for spam
- If it contains “meeting” → clue for not spam  
Naive Bayes combines the clues and picks the most likely answer.

**How this relates to MNIST digits:**  
It treats each pixel as a tiny clue.
- Dark pixels in certain places might suggest “1”
- Dark pixels in other places might suggest “8”

**Strengths (in simple words):**
- Very fast.
- Works well when “clues” are clear and consistent.

**Weaknesses (in simple words):**
- Pixels in an image are connected (shapes), but Naive Bayes treats clues as more independent than they really are.
- So it often doesn’t do as well on raw images.

In [15]:
# MultinomialNB expects non-negative features.
# Since you already normalized to 0..1, DO NOT StandardScale it (would create negatives).
nb_pipe = Pipeline([
    ("model", MultinomialNB())
])

### Training and Evaluation of the models

In [16]:
knn_pipe.fit(X_train, y_train)
evaluate_model(knn_pipe, X_test, y_test, name="k-NN (k=5)")

k-NN (k=5) Results
------------------
Accuracy: 0.9375

Classification report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       827
           1       0.95      1.00      0.97       937
           2       0.95      0.94      0.94       835
           3       0.92      0.93      0.93       870
           4       0.94      0.92      0.93       814
           5       0.91      0.91      0.91       759
           6       0.96      0.97      0.97       827
           7       0.94      0.93      0.93       880
           8       0.97      0.86      0.92       813
           9       0.90      0.92      0.91       838

    accuracy                           0.94      8400
   macro avg       0.94      0.94      0.94      8400
weighted avg       0.94      0.94      0.94      8400

Confusion matrix:
[[811   0   1   1   0   6   6   1   0   1]
 [  0 933   0   1   0   0   2   1   0   0]
 [  8   8 781  14   4   1   5   9   2   3]
 [  4   2  11 811   0  19   2   9   7   5]
 [  0  11   6   2 751   4   4   6   1  29]
 [  6   4   6  24   2 690  10   0   7  10]
 [ 10   1   4   0   1   6 805   0   0   0]
 [  1  12   4   6  13   0   0 816   0  28]
 [ 11  14  11  18   8  30   6   4 703   8]
 [  5   2   0   5  22   3   0  24   3 774]]

0.9375

In [17]:
nb_pipe.fit(X_train, y_train)
evaluate_model(nb_pipe, X_test, y_test, name="Naive Bayes (MultinomialNB)")

Naive Bayes (MultinomialNB) Results
-----------------------------------
Accuracy: 0.8246

Classification report:
              precision    recall  f1-score   support

           0       0.93      0.92      0.93       827
           1       0.89      0.93      0.91       937
           2       0.87      0.85      0.86       835
           3       0.80      0.81      0.80       870
           4       0.84      0.72      0.77       814
           5       0.84      0.64      0.73       759
           6       0.88      0.92      0.90       827
           7       0.96      0.83      0.89       880
           8       0.64      0.77      0.70       813
           9       0.68      0.84      0.75       838

    accuracy                           0.82      8400
   macro avg       0.83      0.82      0.82      8400
weighted avg       0.83      0.82      0.83      8400

Confusion matrix:
[[762   1   4   3   2   8  16   0  28   3]
 [  0 874   3   7   0   4   5   0  43   1]
 [  8   9 706  20   9   2  34   4  41   2]
 [  5  13  51 701   4  19  11   5  43  18]
 [  5   2   2   0 585   2  15   2  39 162]
 [ 18   5   9  96  17 486  18   1  74  35]
 [  5  15  13   0   2  22 757   0  13   0]
 [  3  11   5   4  15   0   1 729  32  80]
 [  5  49  10  39   8  32   6   2 627  35]
 [  6   5   4  10  55   6   0  15  37 700]]

0.8246428571428571

In [ ]:
svm_pipe.fit(X_train, y_train)
evaluate_model(svm_pipe, X_test, y_test, name="Linear SVM")
# We have not run this due to lack of GPU and it would take alot on this big of a Dataset.

# Report for the models
## Model Evaluation Report (MNIST Digits – Classical ML)

### Dataset + Setup (what I did)
- **Task:** Identify handwritten digits (**0–9**) from images stored as pixel values.
- **Data format:** Each image is represented by **784 pixel columns** (28×28 flattened into one row).
- **Split:** Training and testing were separated so the models were tested on **unseen images**.
- **Evaluation method:** I measured overall **accuracy** and also checked per-digit performance (how well each digit was recognized).

---

## 1) k‑Nearest Neighbors (k‑NN, k=5)

### Overall result
- **Accuracy:** **0.9375** (≈ **93.75%**)

### What this means (simple)
k‑NN works by comparing a new digit image to the most similar images it has already seen and then **voting** on the label.  
The high accuracy shows that “similar-looking digits often share the same label,” so this method is naturally strong on MNIST.

### Per-digit highlights (from the report)
- Strong performance on most digits, especially:
  - **Digit 1:** recall ≈ **1.00** (it almost always finds 1 correctly)
  - **Digit 6:** very high precision/recall (very consistent recognition)
- A noticeable weakness:
  - **Digit 8:** recall ≈ **0.86**, meaning the model misses 8 more often than other digits (it likely confuses 8 with digits that have similar shapes like 3, 9, or 0 depending on writing style).

### Key takeaway
- **k‑NN gives strong accuracy on MNIST**, but it can be **slow** because it compares test images to many training images.

---

## 2) Naive Bayes (MultinomialNB)

### Overall result
- **Accuracy:** **0.8246** (≈ **82.46%**)

### What this means (simple)
Naive Bayes predicts using many small “clues” and tries to choose the most likely digit.  
On images, this approach is weaker because the digit is not just a collection of independent pixels — the **shape and structure** matter (pixels work together to form strokes).

### Per-digit highlights (from the report)
- Stronger digits:
  - **0:** precision/recall both around **0.92+**
  - **1:** strong performance around **0.90+**
  - **6:** strong recall around **0.92**
- Weaker digits:
  - **8:** precision ≈ **0.64**, meaning when it predicts “8”, it is wrong more often than for other digits.
  - **5:** recall ≈ **0.64**, meaning it misses many actual 5s.
  - **4:** recall ≈ **0.72**, also comparatively weaker.
  - **9:** precision ≈ **0.68**, meaning 9 is also confused more frequently.

### Key takeaway
- **Naive Bayes is fast**, but **less accurate on raw pixel images** because it doesn’t naturally handle “shape” the way humans do.

---

## Comparison Summary

| Model | Accuracy | Main Strength | Main Limitation |
|------|----------|---------------|-----------------|
| k‑NN (k=5) | **93.75%** | Very strong on image similarity | Can be slow at prediction time |
| Naive Bayes | **82.46%** | Very fast baseline | Struggles with digits that require understanding shape (like 8, 5, 9) |

---

## Final Conclusion
For this MNIST-style pixel dataset:
- **k‑NN performed significantly better than Naive Bayes** because handwritten digits are mainly recognized by **visual similarity**, which k‑NN directly uses.
- **Naive Bayes provides a useful quick baseline**, but its assumptions make it less suitable for image pixels where the meaning comes from the **overall structure** of the digit, not individual pixels alone.

This comparison supports the main learning goal: **classical machine learning can work on images**, but it also shows limitations when the model does not naturally capture the idea of *shape*.

## Now saving the Best Model

In [18]:
import joblib
joblib.dump(knn_pipe, "knn_mnist_model.joblib")
print("k-NN model saved as knn_mnist_model.joblib")

k-NN model saved as knn_mnist_model.joblib